### ISSUE TITLE
Lua scripting

### ISSUE THREAD

**Issue by hfalcke** [carlosonunez/obs-installer-for-apple-silicon#14]
When I start with a clean system it doesn't include Lua scripting. Any chance to include it?

(I manually compiled OBS before and installed the latest luajit beta, then Obs would include scripting, but it would crash after about 2 mins with, e.g. count down timer. I have seen other ARM versions that do seem to work with LUA scripting, but it is not clear how they did it. )

BTW, would it be possible to include other packages like advanced scene switcher or obs-ndi in the compilation? (I managed to compile this manually before and that worked relatively flawlessly).

**Comment by carlosonunez** [comment]
Hi! I'm not fully understanding your problem here, unfortunately. Can you provide logs or some other output to help me better help you?

**Comment by carlosonunez** [comment]
Hey there. It appears that Lua for OBS will need to be compiled separately before being included into this installer. Unfortunately, I cannot make time to add support for this right now. Apologies!

If you're interested in trying to add this feature yourself, I'd start with OBS's CI build scripts, which you can find here: https://raw.githubusercontent.com/obsproject/obs-studio/cf518f4944df6ea1e42f0919b2718b3118582875/.github/workflows/main.yml

I'm going to close this issue for now.
