### ISSUE TITLE
Does not open.

### ISSUE THREAD

**Issue by iambenmitchell** [carlosonunez/obs-installer-for-apple-silicon#15]
After compiling, I try to open the OBS app and it does nothing. Attempting to open it in terminal says:
`zsh: permission denied`

**Comment by lukeshiru** [comment]
I think I'm having the same issue. I'm not able to run the app from `Applications` directly, but if I run this in the terminal, it runs ok: `/Applications/OBS.app/Contents/MacOS/OBS` ... is like there is something wrong with the `.app`, but not with the actual binary.

**Comment by carlosonunez** [comment]
I just built 27.0.1 with no issues. @MrBenFTW , @lukeshiru : Can you copy the logs that get generated after running `./install.sh`? Thank you!

**Comment by WEcompany36** [comment]
Hi! I built this myself. Just treat this like a normal installer.
[obs-27.0.1-for-m1.dmg.zip](https://github.com/carlosonunez/obs-installer-for-apple-silicon/files/7119175/obs-27.0.1-for-m1.dmg.zip)
