### ISSUE TITLE
Error running install.sh: Could NOT find MbedTLS

### ISSUE THREAD

**Issue by allesgroupadmin** [carlosonunez/obs-installer-for-apple-silicon#22]
Log: https://0bin.net/paste/3aef63gl#HTH6SrSLTsZeSVcYT5XuUfd6EtcTqtWq44UQH5rn0YF
This was after removing OBS by dragging the application to the trash and attempting to reinstall it with a new flag.
Error occurs, however, on a freshly cloned folder.

**Comment by carlosonunez** [comment]
This has been fixed in 1.1.0.
