### ISSUE TITLE
Missing file during compile routine

### ISSUE THREAD

**Issue by gargola-dev** [carlosonunez/obs-installer-for-apple-silicon#25]
In file included from /tmp/obs/plugins/obs-outputs/librtmp/rtmp.c:178:
/tmp/obs/plugins/obs-outputs/librtmp/handshake.h:29:10: fatal error: 'mbedtls/arc4.h' file not found
#include <mbedtls/arc4.h>
         ^~~~~~~~~~~~~~~~
1 error generated.
make[2]: *** [plugins/obs-outputs/CMakeFiles/obs-outputs.dir/librtmp/rtmp.c.o] Error 1
make[1]: *** [plugins/obs-outputs/CMakeFiles/obs-outputs.dir/all] Error 2
make: *** [all] Error 2
[Wed Oct 13 12:52:04 CEST 2021] FATAL: Unable to build OBS; see above logs for more info. Try running this instead: REPACKAGE=true ./install.sh

**Comment by carlosonunez** [comment]
Merged; closing.
