### ISSUE TITLE
VirtualCam DAL Plugin missing

### ISSUE THREAD

**Issue by simonbunge** [carlosonunez/obs-installer-for-apple-silicon#26]
I follow the instructions to compile based on a vanilla (other than fixing per [Issue #25](https://github.com/carlosonunez/obs-installer-for-apple-silicon/issues/25)) install.sh, I end up with a beautiful native application bundle.
However, the Virtual Camera doesn't load as per the following main log extract:

```
13:36:56.881: [mac-virtualcam] version=1.3.0
13:39:40.601: [mac-virtualcam] [macOS] VirtualCam DAL Plugin not shipped with OBS
```

Any ideas appreciated!

**Comment by simonbunge** [comment]
So that directory actually shows up one level higher, see here:

<img width="518" alt="Screen Shot 2021-10-17 at 9 02 28 AM" src="https://user-images.githubusercontent.com/13904873/137600813-56b93e24-7bd7-47c1-aff7-6058f45d6bcb.png">

Pushing it down two levels with `mv OBS.app/Contents/Resources/data/obs-mac-virtualcam.plugin OBS.app/Contents/Resources/data/obs-plugins/mac-virtualcam` does the trick, though! 👍🏻  

<img width="781" alt="Screen Shot 2021-10-17 at 9 18 30 AM" src="https://user-images.githubusercontent.com/13904873/137601137-90832564-253e-420d-9b1e-04ecdf16aaff.png">
 
I suppose this gives you an idea of what needs fixing?

**Comment by carlosonunez** [comment]
Yes it does! I can handle this one!

Thank you for all of your hard work here.

**Comment by simonbunge** [comment]
No, thank _you_, Sir. Albeit the main project appears to be pretty close to native support (see [the latest on build scripts targeting universal]( https://github.com/obsproject/obs-studio/commit/ba482ea80980387540c5b38b4d56b1593c0002b7)), this project is an amazing effort!

**Comment by carlosonunez** [comment]
Believe me i can't wait to deprecate this lol
