### ISSUE TITLE
VirtualCam DAL Plugin not shipped with OBS

### ISSUE THREAD

**Issue by blineadam** [carlosonunez/obs-installer-for-apple-silicon#31]
When trying to start a virtual camera obs 27.1.3 clicking the button does nothing and in the logs I see
14:20:12.476: [mac-virtualcam] [macOS] VirtualCam DAL Plugin not shipped with OBS
14:20:12.598: [mac-virtualcam] [macOS] VirtualCam DAL Plugin not shipped with OBS

Do I need to install an older version then 27.0.3 or is there an install step that was missed?

[2021-11-02 14-19-17.txt](https://github.com/carlosonunez/obs-installer-for-apple-silicon/files/7463185/2021-11-02.14-19-17.txt)
?

**Comment by blineadam** [comment]
I was able to fix this by moving the plugin into the old plugin locations

By creating the following directories
```
sudo mkdir -p /Library/CoreMediaIO/Plug-Ins/DAL/obs-mac-virtualcam.plugin
sudo mkdir -p /Library/Application\ Support/obs-studio/plugins/obs-mac-virtualcam
```
running the install with the 
`REMOVE_INSTALLATION_DIRS=false ./install.sh`

Then copying the folders to the old plugin locations 
```
sudo cp -r /tmp/obs/cmake/_CPack_Packages/Darwin/Bundle/obs-studio-x64-27.1.3-modified/OBS.app/Contents/Resources/data/obs-mac-virtualcam.plugin/Contents/MacOS/obs-mac-virtualcam /Library/Application\ Support/obs-studio/plugins/.
sudo cp -r /tmp/obs/cmake/plugins/mac-virtualcam/src/dal-plugin/obs-mac-virtualcam.plugin /Library/CoreMediaIO/Plug-Ins/DAL/obs-mac-virtualcam.plugin/.
```

**Comment by DenisSergeevitch** [comment]
Still not working for me unfortunately under macOS Monterey, even with a method above

**Comment by DenisSergeevitch** [comment]
This fix works: https://github.com/carlosonunez/obs-installer-for-apple-silicon/issues/26#issuecomment-945002099
