### ISSUE TITLE
Add Qt as a brew dependencie

### ISSUE THREAD

**Issue by skhalymon** [carlosonunez/obs-installer-for-apple-silicon#32]
The script fails if Qt is not installed with the following error:
```
/tmp/obs/cmake ~/Projects/ALLATRA/obs-installer-for-apple-silicon
-- OBS_VERSION: 27.1.3-modified
CMake Error at CMakeLists.txt:257 (find_package):
  By not providing "FindQt5Widgets.cmake" in CMAKE_MODULE_PATH this project
  has asked CMake to find a package configuration file provided by
  "Qt5Widgets", but CMake did not find one.

  Could not find a package configuration file provided by "Qt5Widgets" with
  any of the following names:

    Qt5WidgetsConfig.cmake
    qt5widgets-config.cmake

  Add the installation prefix of "Qt5Widgets" to CMAKE_PREFIX_PATH or set
  "Qt5Widgets_DIR" to a directory containing one of the above files.  If
  "Qt5Widgets" provides a separate development package or SDK, be sure it has
  been installed.
```

Should we install Qt as install FFmpeg with brew?

**Comment by krolhm** [comment]
same... did you find an alternative ?

**Comment by carlosonunez** [comment]
`qt` and `ffmpeg` are installed with this script; see [here](https://github.com/carlosonunez/obs-installer-for-apple-silicon/blob/main/install.sh#L232-L233)

Can you run this to give me the current version of your clone for `obs-installer-for-apple-silicon`?

```sh
$: git log -1 --format=%h
```

**Comment by skhalymon** [comment]
result of `git log -1 --format=%h`: 0733999

qt and ffmpeg are present in install.sh script

**Comment by carlosonunez** [comment]
Thanks. It looks like you're using the latest version.

Can you re-run the installer using the command below, copy the log and paste it here? 

```sh
LOG_LEVEL=DEBUG ./install.sh
```

**Comment by carlosonunez** [comment]
Closing due to staleness. Re-open with the logs per the comment above if needed.
