### ISSUE TITLE
Adding OBS-NDI in the build?

### ISSUE THREAD

**Issue by anxuanzi** [carlosonunez/obs-installer-for-apple-silicon#34]
Hi, when building OBS can you also add the obs-ndi plugin into the build? I used their installer to install the plugin, but it is not working.

link: https://github.com/Palakis/obs-ndi

Thank you so much for making this installing script!

**Comment by carlosonunez** [comment]
Hey there, @anxuanzi! Thank you for raising this issue.

Unfortunately, I will not be able to fulfill your request. This script will only install ARM-native OBS and the plugins it comes with to remain compatible with upstream.

Please speak with the developer of the plugin you are trying to install if you need support.

I'll be closing this issue now. Thanks for understanding.
