### ISSUE TITLE
OBS Lua scripting support

### ISSUE THREAD

**Issue by pawelwiejkut** [carlosonunez/obs-installer-for-apple-silicon#36]
Hello,

Is it possible to build easily OBS on M1 with Lua support? I'm missing this...

Thank you for your support.

**Comment by carlosonunez** [comment]
Hey there, @pawelwiejkut ! Thank you for raising this issue.

Unfortunately, I will not be able to fulfill your request. This script will only install ARM-native OBS and the plugins it comes with to remain compatible with upstream.

Please speak with the developer of the plugin you are trying to install if you need support.

I'll be closing this issue now. Thanks for understanding.
