### ISSUE TITLE
Device not connected or not avaliable

### ISSUE THREAD

**Issue by kubai087** [carlosonunez/obs-installer-for-apple-silicon#37]
<img width="1171" alt="iShot2021-11-16 21 18 18" src="https://user-images.githubusercontent.com/68949228/141992444-acf2beeb-f57f-4362-992d-b758d74d9574.png">

I already gave the necessary permission like screen recording to the software and restarted it for a few times, but it remains still.
 Hopefully it could be fixed <3

**Comment by kubai087** [comment]
My device is Macbook Pro 2021 14' with M1 max 10-core CPU,24-core GPU and 32 GB RAM

**Comment by xieyx** [comment]
me too

**Comment by xieyx** [comment]
I fixed it, try re-auth screen record.

**Comment by kubai087** [comment]
> I fixed it, try re-auth screen record.

I tried this method, but it remains the same.

**Comment by carlosonunez** [comment]
Hello! Are you still having this issue?

**Comment by kubai087** [comment]
> Hello! Are you still having this issue?

yes

**Comment by carlosonunez** [comment]
Can you try building the latest version available?

**Comment by kubai087** [comment]
> Can you try building the latest version available?

ok

**Comment by kubai087** [comment]
> Can you try building the latest version available?

It remains the same.

**Comment by carlosonunez** [comment]
Can you try building the experimental OBS version per the README and see if you can replicate?

**Comment by kubai087** [comment]
> Can you try building the experimental OBS version per the README and see if you can replicate?
> […](#)
> On Jan 24, 2022, 19:16 -0600, 枯白 ***@***.***>, wrote: > Can you try building the latest version available? It remains the same. — Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because yo
<img width="665" alt="iShot2022-01-25 10 57 17" src="https://user-images.githubusercontent.com/68949228/150902710-f0d156c7-1d75-48b5-8f0d-dade9f9d56b7.png">
u modified the open/close state.Message ID: ***@***.***>

**Comment by carlosonunez** [comment]
Can you run this script in Bash instead of zsh? To do that, prepend install.sh with “bash”.

**Comment by kubai087** [comment]
> 

Same

**Comment by carlosonunez** [comment]
which is the same? the error you got last time or the original error that started this issue?

**Comment by kubai087** [comment]
> which is the same? the error you got last time or the original error that started this issue?
> […](#)
> On Jan 25, 2022, 05:05 -0600, 枯白 ***@***.***>, wrote: Same — Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you modified the open/close state.Message ID: ***@***.***>

The erro I got last time on terminal

**Comment by kubai087** [comment]
I fixed the issue! To make the obs work properly, there are a few steps to follow.
1. Right click the obs.app in the Application folder.
2. Open finder, press cmd+shift+G, paste ~/Library/Application Support and press Enter to navigate to the folder.
3. Delele the obs-studio folder.
4. Open System Preference, go to Safety and Privacy (安全性和隐私), go to the Screen Recording Permission Tab, press "-" to remove obs
5. Open the terminal, paste`brew install akeru-inc/tap/xcnotary cmake cmocka ffmpeg jack mbedtls qt@5 swig vlc` (The Homebrew should be installed first)
6. Build OBS again and install it.
7. When you first open OBS, it will toast to ask you for screen recording permission. Give it the permission.
8. Then the OBS will work properly.

**Comment by carlosonunez** [comment]
That’s fantastic! Thanks for writing down your solution. I’ll add it to the README.
