### ISSUE TITLE
Virtual camera not working

### ISSUE THREAD

**Issue by lucouto** [carlosonunez/obs-installer-for-apple-silicon#38]
I've just run the script and installed OBS successfully on my M1 Mac mini. But the Virtual Camera in not working. When I click "Start Virtual Camera" the button blinks and doesn't activate. 

Any easy way to debug this, please?

TIA,
L.

**Comment by woogli** [comment]
I've just tried this for the first time and the virtual camera won't start for me either.  I'm on a new 14" Macbook Pro with M1 Max (24-core).

**Comment by typeRob** [comment]
Compiled this few days ago, I've got the same issue. If I click on the "start virtual camera" button it does nothing. I'm on a MBP 13 with M1

**Comment by carlosonunez** [comment]
Can you please run this command and provide me with the output?

```sh
find /Applications/OBS.app -name *virtualcam*
```

**Comment by ambirex** [comment]
I just compiled it and when I run the find command I get `zsh: no matches found: *virtual*`

Here is log from running the install script - https://gist.github.com/ambirex/bbc444186fcd0933cb974245ffc3c9d9

**Comment by typeRob** [comment]
This is my output:

/Applications/OBS.app//Contents/Resources/obs-plugins/mac-virtualcam.so
/Applications/OBS.app//Contents/Resources/data/obs-plugins/mac-virtualcam
/Applications/OBS.app//Contents/Resources/data/obs-mac-virtualcam.plugin
/Applications/OBS.app//Contents/Resources/data/obs-mac-virtualcam.plugin/Contents/MacOS/obs-mac-virtualcam

**Comment by lucouto** [comment]
Results from `find /Applications/OBS.app -name *virtualcam*` here:

>/Applications/OBS.app/Contents/Resources/obs-plugins/mac-virtualcam.so
/Applications/OBS.app/Contents/Resources/data/obs-plugins/mac-virtualcam
/Applications/OBS.app/Contents/Resources/data/obs-mac-virtualcam.plugin
/Applications/OBS.app/Contents/Resources/data/obs-mac-virtualcam.plugin/Contents/MacOS/obs-mac-virtualcam

There were some warnings during the compilation process. Maybe the log can help you debug this.
[install_log.txt](https://github.com/carlosonunez/obs-installer-for-apple-silicon/files/7649147/install_log.txt)
[Terminal Saved Output.txt](https://github.com/carlosonunez/obs-installer-for-apple-silicon/files/7649150/Terminal.Saved.Output.txt)

**Comment by richardpeng** [comment]
I had this same issue. For some reason, there's no `/Library/CoreMediaIO/Plug-Ins/DAL` folder after running `install.sh`.

I was able to get things working by manually copying the virtualcam plugin:

`sudo rsync -ahP ./obs/cmake/_CPack_Packages/Darwin/Bundle/obs-studio-x64-27.1.3-modified/OBS.app/Contents/Resources/data/obs-mac-virtualcam.plugin/Contents/ /Library/CoreMediaIO/Plug-Ins/DAL/obs-mac-virtualcam.plugin/Contents/`

**Comment by typeRob** [comment]
> I had this same issue. For some reason, there's no `/Library/CoreMediaIO/Plug-Ins/DAL` folder after running `install.sh`.
> 
> I was able to get things working by manually copying the virtualcam plugin:
> 
> `sudo rsync -ahP ./obs/cmake/_CPack_Packages/Darwin/Bundle/obs-studio-x64-27.1.3-modified/OBS.app/Contents/Resources/data/obs-mac-virtualcam.plugin/Contents/ /Library/CoreMediaIO/Plug-Ins/DAL/obs-mac-virtualcam.plugin/Contents/`

Tried this solution and it worked! Don't know why when I copied the whole .plugin file in the DAL folder didn't worked, but copying the Contents folder inside did the job. Thanks

**Comment by lucouto** [comment]
I can confirm that manually copying the files from OBS.app to /Library/ fixes the Virtual Camera issue.
`sudo rsync -ahP /Applications/OBS.app/Contents/Resources/data/obs-mac-virtualcam.plugin/Contents/ /Library/CoreMediaIO/Plug-Ins/DAL/obs-mac-virtualcam.plugin/Contents/`
