### ISSUE TITLE
how to install ndi plugin

### ISSUE THREAD

**Issue by redstyle82** [carlosonunez/obs-installer-for-apple-silicon#39]
Hello! Thanks for your hard work! How can i install the ndi plugin for obs? If i install the one that i use with the "obs rosetta" it just doest appear on the native obs... And i need it! Thanks a lot

**Comment by carlosonunez** [comment]
Hey there, @redstyle82! Thank you for raising this issue.

Unfortunately, I will not be able to fulfill your request. This script will only install ARM-native OBS and the plugins it comes with to remain compatible with upstream.

Please speak with the developer of the plugin you are trying to install if you need support.

I'll be closing this issue now. Thanks for understanding.
