### ISSUE TITLE
Build fails  on missing libvlc.h

### ISSUE THREAD

**Issue by shrubberies** [carlosonunez/obs-installer-for-apple-silicon#42]
40%] Building C object plugins/vlc-video/CMakeFiles/vlc-video.dir/vlc-video-plugin.c.o
In file included from /tmp/obs/plugins/vlc-video/vlc-video-plugin.c:6:
/tmp/obs/plugins/vlc-video/vlc-video-plugin.h:2:10: fatal error: 'libvlc.h' file not found
#include <libvlc.h>
         ^~~~~~~~~~
1 error generated.
make[2]: *** [plugins/vlc-video/CMakeFiles/vlc-video.dir/vlc-video-plugin.c.o] Error 1
make[1]: *** [plugins/vlc-video/CMakeFiles/vlc-video.dir/all] Error 2
make: *** [all] Error 2

**Comment by carlosonunez** [comment]
Is `vlc` installed? `brew info vlc`

**Comment by shrubberies** [comment]
MacBook-Air ~ % brew info vlc
vlc: 3.0.16 (auto_updates)
https://www.videolan.org/vlc/
/opt/homebrew/Caskroom/vlc/3.0.16 (2 files, 49.6KB)
From: https://github.com/Homebrew/homebrew-cask/blob/HEAD/Casks/vlc.rb
==> Name
VLC media player
==> Description
Multimedia player
==> Artifacts
VLC.app (App)
/opt/homebrew/Caskroom/vlc/3.0.16/vlc.wrapper.sh -> vlc (Binary)
==> Analytics
install: 8,470 (30 days), 25,102 (90 days), 93,969 (365 days)

**Comment by carlosonunez** [comment]
Do you get the same result when you `git pull` the latest commit from `main`?

**Comment by mikeev261** [comment]
I'm getting the same when building from master, or one of the recent 27.2 beta releases. 

Building from default (27.1.3) works fine. So this seems to be an issue with the newer commits in the repo.

**Comment by carlosonunez** [comment]
Okay, thanks. Perhaps one of their dependencies changed. I'll try building against that release to see what's up.

**Comment by mikeev261** [comment]
Anyone have luck figuring this one out yet?

**Comment by carlosonunez** [comment]
Thanks for using my script! I was able to repro and am pushing a fix later today.

**Comment by carlosonunez** [comment]
Confirmed resolved. Please re-raise if you are still encountering this issue. Thanks!
