### ISSUE TITLE
Experimental build stuck 

### ISSUE THREAD

**Issue by EthanSK** [carlosonunez/obs-installer-for-apple-silicon#43]
It gets stuck on 

In order to fetch OBS from GitHub Actions, you'll need to authorize the application that you created. Click this URL or copy/paste it into your browser to do that:

What do I provide as the callback url for the github app?

**Comment by carlosonunez** [comment]
Click or copy/paste the URL that shows up. After you authorize, you should see something like this in your browser:

“Thanks. Go back to your Terminal to continue installing OBS."

And the installation should continue automatically.

**Comment by EthanSK** [comment]
I do copy and paste. I set some random callback url. I authorize, and everything, but nothing happens in the terminal after that.

**Comment by carlosonunez** [comment]
what happens when you run this: which nc?

**Comment by EthanSK** [comment]
/usr/bin/nc

**Comment by loveJesus** [comment]
God is good, thanks for the script, having the same problem here (not sure which url to provide for the app callback, does it need to be like an ngrok to this machine?

**Comment by dvcrn** [comment]
The instruction don't make this clear but looking at the code it creates a server listening to port 4567. You need to set the callback to localhost:4567

https://github.com/carlosonunez/obs-installer-for-apple-silicon/blob/main/install.sh#L584

**Comment by dvcrn** [comment]
Added it to the readme - https://github.com/carlosonunez/obs-installer-for-apple-silicon/pull/46

**Comment by carlosonunez** [comment]
Fixed; closed. Thanks, @dvcrn !
