### ISSUE TITLE
why is 'sh' asking for permission for keystrokes instead of OBS?

### ISSUE THREAD

**Issue by mycroftcanner** [carlosonunez/obs-installer-for-apple-silicon#48]
![image](https://user-images.githubusercontent.com/55385694/152277582-38b8fa7e-b091-445c-b746-ae1bc21187d4.png)

The official x64 build has OBS asking for privacy authorisations.

**Comment by carlosonunez** [comment]
Hello! Thanks for using my script.

To be honest, I'm not entirely sure. This might have something to do with code signing (which I'm not doing, as I don't have the ability to do so).

I don't do any modification of the `CMakefile` or OBS sources aside from what's coming from OBS. You can verify the source here to confirm.

**Comment by carlosonunez** [comment]
I looked into this. If you take a look at `/Applications/OBS.app/Contents/MacOS/OBS`, you'll see that it's a shell script that forks `obs` with some context. If this is problematic for you, use the experimental build.
