### ISSUE TITLE
No video sources available

### ISSUE THREAD

**Issue by OptimusKoala** [carlosonunez/obs-installer-for-apple-silicon#52]
Hello, 

I followed the doc but I can't have my screen sources working. 
I tried this solution -> #37 but it's not working for me. 

OBS Studio never ask me for permissions even after I fully cleaned up(~/Library/Application Support/obs-studio). 

I should have a lot of sources here:
<img width="1142" alt="Capture d’écran 2022-03-03 à 11 14 24" src="https://user-images.githubusercontent.com/9715596/156550804-dd70cce9-6dc1-4219-b50b-9a187a5e48f7.png">

And here my main screen isn't available:
<img width="1071" alt="Capture d’écran 2022-03-03 à 11 54 39" src="https://user-images.githubusercontent.com/9715596/156551024-7e07a0c2-b1ca-4ec5-a1e5-bbbe1708a346.png">

I'm trying on a 2021 iMac M1.

**Comment by fabltd** [comment]
+1

**Comment by TuxTheAstronaut** [comment]
im having the same issue here too no matter what i do obs cant record my screen

**Comment by carlosonunez** [comment]
That's very strange, as I can't reproduce this in the build I'm running. I'll try a new build and report back.

**Comment by carlosonunez** [comment]
Okay, I was able to reproduce this. I have a workaround.

1. Go to `Security & Privacy`. Navigate to the `Privacy` tab, then click on `Screen Recording` to the left.
2. If `sh` is checked, uncheck it, then quit OBS.
3. Check `sh`, then open OBS.

## Why does OBS ask for permissions through `sh`?

The Mac app that gets built with these instructions aliases the OBS executable inside of `/Applications/OBS.app/Contents/MacOS` to a shell script that opens OBS with some context. Consequently, this makes `sh` the parent process running OBS.

If this is an issue, use the experimental build.
