### ISSUE TITLE
SteamDeck Plugin

### ISSUE THREAD

**Issue by fabltd** [carlosonunez/obs-installer-for-apple-silicon#57]
Thank you for your work.

I have the M! native build working. However I use a StreamDeck and it doesn't appear to be able to find the OBS installation. I also tryied some other plugins and these are not showing up. Any idea how to debug?

**Comment by fabltd** [comment]
Checked the logs.

I found an earlier issue where it seems this build loads plugins from a different location but I cannot find out where that should be. 

Any suggestions?

**Comment by carlosonunez** [comment]
Hey, @fabltd! Thanks for using this project!

I don't support plug-ins that are not built into OBS, as reproducing errors and writing tests will them will consume more time than I can commit to. As such, I'm going to close this issue. However, one thing you can try is ensuring that your plugin is located in `/Applications/OBS.app/Contents/Resources/data/obs-plugins/`.

Good luck!
