### ISSUE TITLE
Speex/RRNoise Noise Suppression not available to select. 

### ISSUE THREAD

**Issue by FieryEarth** [carlosonunez/obs-installer-for-apple-silicon#8]
When I add noise suppression, it doesnt give me options to select or control anything. While on MMdisc' version I can select between Speex and RRNoise, as well as control speex %.

**Comment by carlosonunez** [comment]
This was fixed a few commits ago. Give it another try!

**Comment by abohw** [comment]
This still doesn't work for me.
