### ISSUE TITLE
no vlc source

### ISSUE THREAD

**Issue by fbosman** [carlosonunez/obs-installer-for-apple-silicon#9]
Hi,
thank you for your work!
I managed to compile OBS, but I cannot use a VLC source, there is no sourcetype vlc available.

**Comment by hfalcke** [comment]
I added        -DVLC_INCLUDE_DIR=/opt/homebrew/Caskroom/vlc/3.0.16/VLC.app/Contents/MacOS/include/vlc \
after cmake -DCMAKE_OSX_DEPLOYMENT_TARGET=10.13 -DDISABLE_PYTHON=ON \

then it seems to find it.

**Comment by carlosonunez** [comment]
Please submit a PR with this fix; thank you!
